flags: {}
packages:
- .
allow-newer: true
extra-deps:
- hedgehog-1.0
- http2-client-0.9.0.0
- jwt-0.10.0
- prometheus-metrics-ghc-1.0.0
- wai-middleware-prometheus-1.0.0
- git: https://github.com/syallop/Pusher-Platform-Haskell.git
  commit: c33d86963aa5eba7ca54b2b2386aaeb5a12b6c16
resolver: lts-14.20

